Repository compose-generator/compose-generator, pull requests merged in 2021-11, with the labels that each got.

#197 Fix bug with wrong log dir on Windows
  .github/workflows/publish.yml
  .goreleaser.yml
  README.md
  src/util/cli.go
  src/util/env.go
  src/util/env_test.go
  src/util/mock_functions.go
  src/util/text.go
Labels: bug, size/L

#196 Predefined service: AdGuard Home
  .github/scripts/service-tester/predefined-service-tester.py
  docs/docs/supported-services.md
  predefined-services/backend/adguard-home/README.md
  predefined-services/backend/adguard-home/config.json
  predefined-services/backend/adguard-home/service.yml
Labels: predefined-service, size/L

#200 Convert issue templates to forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: documentation, size/L

#203 Fix CentOS and Fedora repo deployment
  .github/scripts/service-tester/predefined-service-tester.py
  .github/workflows/publish.yml
Labels: bug, improvement, size/XS

#201 Predefined service: Accent
  docs/docs/supported-services.md
  predefined-services/database/postgres/config.json
  predefined-services/database/postgres/service.yml
  predefined-services/db-admin/adminer/service.yml
  predefined-services/db-admin/elasticsearch-hq/service.yml
  predefined-services/db-admin/pgadmin/service.yml
  predefined-services/db-admin/phpmyadmin/service.yml
  predefined-services/frontend/accent/README.md
  predefined-services/frontend/accent/config.json
  predefined-services/frontend/accent/environment.env
  predefined-services/frontend/accent/service.yml
  predefined-services/tls-helper/letsencrypt/service.yml
Labels: predefined-service, size/L

#204 Predefined service: Plex
  docs/docs/supported-services.md
  predefined-services/backend/plex/README.md
  predefined-services/backend/plex/config.json
  predefined-services/backend/plex/service.yml
Labels: predefined-service, size/M

#198 Extend predefined services Readme
  docs/docs/install/linux.md
  predefined-services/README.md
Labels: documentation, size/M

#205 Fix copy bug with custom volume / build context dir
  src/cmd/generate.go
  src/cmd/generate_test.go
  src/model/predefined-template.go
  src/pass/generate/gen_copy_volumes.go
  src/pass/generate/gen_copy_volumes_test.go
  src/pass/generate/gen_replace_placeholders.go
  src/pass/generate/gen_replace_placeholders_test.go
Labels: bug, size/L

#206 Fix auto dependencies
  src/pass/generate/gen_copy_volumes.go
  src/pass/generate/gen_copy_volumes_test.go
  src/pass/generate/gen_generate.go
Labels: bug, improvement, size/M

#199 Predefined service: Pi-hole
  .github/scripts/service-tester/predefined-service-tester.py
  .github/scripts/service-validator/service-schema.py
  predefined-services/backend/pi-hole/README.md
  predefined-services/backend/pi-hole/config.json
  predefined-services/backend/pi-hole/environment.env
  predefined-services/backend/pi-hole/service.yml
Labels: predefined-service, size/M

#207 Predefined service: Pi-hole
  .github/scripts/service-tester/predefined-service-tester.py
  .github/scripts/service-validator/service-schema.py
  docs/docs/supported-services.md
  predefined-services/backend/pi-hole/README.md
  predefined-services/backend/pi-hole/config.json
  predefined-services/backend/pi-hole/environment.env
  predefined-services/backend/pi-hole/service.yml
Labels: predefined-service, size/L

#208 Centos fedora repo deploy
  .github/workflows/publish.yml
Labels: bug, size/XS

#209 Remove npm installation method temporarily
  docs/docs/quick-start.md
  docs/docs/usage/install.md
  docs/mkdocs.yml
  media/readme-dockerhub.md
Labels: documentation, size/S

#210 Prepare for release
  docs/docs/supported-services.md
  package-lock.json
  package.json
Labels: documentation, size/M

#211 Apply Goreportcard suggestions
  src/cmd/generate.go
  src/pass/generate/gen_generate_test.go
  src/pass/generate/gen_load_config_test.go
  src/project/delete_options.go
  src/project/load_options.go
  src/project/save_options.go
  src/util/questions.go
Labels: improvement, size/S

#212 Command to delete custom templates
  .github/dependabot.yml
  media/readme-dockerhub.md
  src/cmd/mock_functions.go
  src/cmd/template-delete.go
  src/cmd/template-delete_test.go
  src/cmd/template-load.go
  src/cmd/template-load_test.go
  src/compose-generator.go
Labels: documentation, enhancement, size/L

#214 Add support for auto-completion
  .goreleaser.yml
  bash_autocomplete.sh
  src/compose-generator.go
Labels: enhancement, improvement, size/S

#215 Add support for customizable secrets
  .github/scripts/service-validator/config-schema.py
  predefined-services/backend/pi-hole/config.json
  predefined-services/db-admin/pgadmin/config.json
  src/model/predefined-template.go
  src/pass/generate/gen_choose_backends.go
  src/pass/generate/gen_choose_backends_test.go
  src/pass/generate/gen_choose_databases.go
  src/pass/generate/gen_choose_databases_test.go
  src/pass/generate/gen_choose_db_admin.go
  src/pass/generate/gen_choose_db_admin_test.go
  src/pass/generate/gen_choose_frontends.go
  src/pass/generate/gen_choose_frontends_test.go
  src/pass/generate/gen_secrets.go
  src/pass/generate/mock_functions.go
  src/util/mock_functions.go
  src/util/questions.go
  src/util/templates.go
Labels: enhancement, size/M

#217 Fix bug with bind volumes on Windows
  src/pass/generate/gen_copy_volumes.go
Labels: bug, size/XS

#218 Prepare for release
  .github/ISSUE_TEMPLATE/bug_report.yml
  media/readme-dockerhub.md
  package-lock.json
  package.json
Labels: documentation, size/XS

#219 Release of version 1.2.1
  .github/ISSUE_TEMPLATE/bug_report.yml
  media/readme-dockerhub.md
  package-lock.json
  package.json
  src/pass/generate/gen_copy_volumes.go
Labels: release, size/S

#216 New predefined template dev command
  .gitignore
  src/cmd/cmd.go
  src/cmd/generate.go
  src/cmd/mock_functions.go
  src/cmd/predefined-template-new.go
  src/cmd/predefined-template-new_test.go
  src/compose-generator.go
  src/model/predefined-template.go
  src/pass/generate/gen_choose_backends_test.go
  src/pass/generate/gen_choose_databases_test.go
  src/pass/generate/gen_choose_db_admin_test.go
  src/pass/generate/gen_choose_frontends_test.go
  src/pass/generate/gen_copy_volumes_test.go
  src/pass/generate/gen_dependency_groups_test.go
  src/pass/generate/gen_load_config_test.go
Labels: enhancement, improvement, size/L

#222 Update service template versions
  predefined-services/backend/django/config.json
  predefined-services/backend/nexus/config.json
  predefined-services/backend/pi-hole/config.json
  predefined-services/backend/prometheus/config.json
  predefined-services/backend/rocket/config.json
  predefined-services/database/influxdb/config.json
  predefined-services/database/questdb/config.json
  predefined-services/database/scylladb/config.json
  predefined-services/frontend/gitlab/config.json
  predefined-services/frontend/grafana/config.json
  predefined-services/frontend/jupyter/config.json
  predefined-services/frontend/uptime-kuma/config.json
  predefined-services/frontend/youtrack/config.json
  predefined-services/proxy/traefik/config.json
Labels: dependencies, size/S

#224 Predefined service: Ghost
  docs/docs/supported-services.md
  predefined-services/database/mysql/config.json
  predefined-services/database/mysql/service.yml
  predefined-services/frontend/ghost/README.md
  predefined-services/frontend/ghost/config.json
  predefined-services/frontend/ghost/environment.env
  predefined-services/frontend/ghost/service.yml
  src/cmd/mock_functions.go
  src/cmd/predefined-template-new.go
  src/cmd/predefined-template-new_test.go
  src/pass/generate/gen_generate.go
Labels: bug, predefined-service, size/L

#225 Predefined service: Drupal
  docs/docs/supported-services.md
  predefined-services/database/mysql/config.json
  predefined-services/database/mysql/service.yml
  predefined-services/frontend/drupal/README.md
  predefined-services/frontend/drupal/config.json
  predefined-services/frontend/drupal/service.yml
  predefined-services/frontend/drupal/volumes/drupal-sites/default/default.settings.php
  predefined-services/frontend/drupal/volumes/drupal-sites/default/settings.php
Labels: predefined-service, size/XXL

#226 Predefined service: Mediawiki
  .github/workflows/publish.yml
  docs/docs/supported-services.md
  predefined-services/database/mysql/config.json
  predefined-services/database/mysql/service.yml
  predefined-services/frontend/drupal/config.json
  predefined-services/frontend/drupal/volumes/drupal-sites/default/default.settings.php
  predefined-services/frontend/drupal/volumes/drupal-sites/default/settings.php
  predefined-services/frontend/mediawiki/README.md
  predefined-services/frontend/mediawiki/config.json
  predefined-services/frontend/mediawiki/service.yml
  src/pass/generate/gen_secrets.go
  src/util/templates.go
Labels: bug, predefined-service, size/M

#227 Traefik template improvement
  predefined-services/proxy/traefik/README.md
Labels: documentation, improvement

#228 Fix template list
  src/cmd/template-load_test.go
Labels: improvement, tests, size/S

#229 Prepare for release
  README.md
  docs/docs/supported-services.md
  docs/mkdocs.yml
  package-lock.json
  package.json
Labels: documentation, size/M

#230 Predefined service: Monica
  docs/docs/supported-services.md
  predefined-services/backend/monica/README.md
  predefined-services/backend/monica/config.json
  predefined-services/backend/monica/environment.env
  predefined-services/backend/monica/service.yml
  predefined-services/database/mysql/config.json
  src/cmd/template-load_test.go
Labels: bug, predefined-service, size/L

#231 Documentation updates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/dependabot.yml
  README.md
  media/readme-dockerhub.md
  package-lock.json
  package.json
Labels: documentation, size/S

#239 Goreleaser update
  .github/workflows/publish.yml
  .goreleaser.yml
Labels: documentation, size/XS

#240 Fix logfile location
  .goreleaser.yml
  src/util/env.go
  src/util/env_test.go
  src/util/logging.go
Labels: bug, size/XS

#241 Prepare for release
  docs/docs/supported-services.md
  docs/mkdocs.yml
Labels: documentation, size/M

#235 Release of version 1.4.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/dependabot.yml
  .github/scripts/service-tester/predefined-service-tester.py
  .github/workflows/publish.yml
  .goreleaser.yml
  Dockerfile
  README.md
  docs/docs/supported-services.md
  docs/mkdocs.yml
  media/readme-dockerhub.md
  package-lock.json
  package.json
  predefined-services/backend/aspnet/config.json
  predefined-services/backend/monica/README.md
  predefined-services/backend/monica/config.json
  predefined-services/backend/monica/environment.env
  predefined-services/backend/monica/service.yml
  predefined-services/backend/spring-gradle/config.json
  predefined-services/backend/spring-maven/config.json
  predefined-services/backend/teamspeak/README.md
  predefined-services/backend/teamspeak/config.json
  predefined-services/backend/teamspeak/environment.env
  predefined-services/backend/teamspeak/service.yml
  predefined-services/backend/teamspeak/volumes/teamspeak-data/blacklist.txt
  predefined-services/backend/teamspeak/volumes/teamspeak-data/whitelist.txt
  predefined-services/database/mariadb/config.json
  predefined-services/database/mysql/config.json
  src/cmd/template-load_test.go
  src/go.mod
  src/go.sum
  src/util/env.go
  src/util/env_test.go
  src/util/logging.go
  src/vendor/github.com/compose-spec/compose-go/loader/full-example.yml
  src/vendor/github.com/compose-spec/compose-go/loader/loader.go
  src/vendor/github.com/compose-spec/compose-go/loader/merge.go
  src/vendor/github.com/compose-spec/compose-go/loader/volume.go
  src/vendor/github.com/compose-spec/compose-go/template/template.go
  src/vendor/github.com/compose-spec/compose-go/types/project.go
  src/vendor/github.com/compose-spec/compose-go/types/types.go
  src/vendor/github.com/compose-spec/godotenv/godotenv.go
  src/vendor/github.com/compose-spec/godotenv/parser.go
  src/vendor/modules.txt
Labels: release, size/L

#245 Docs version migration
  .github/workflows/docs.yml
  docs/mkdocs.yml
Labels: bug, size/XS
