Repository compose-generator/compose-generator, pull requests merged in 2022-07, with the labels that each got.

#353 Remove/Replace duplicated service Gitlab with Gitea
  docs/docs/supported-services.md
Labels: size/XS

#354 Workflow dependency upgrades
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: enhancement, dependencies, size/S

#355 Use Traefik as default proxy
  predefined-services/proxy/nginx/config.json
  predefined-services/proxy/traefik/config.json
Labels: predefined-service, size/XS

#356 Prepare for update
  .github/dependabot.yml
  README.md
  docs/docs/supported-services.md
  docs/mkdocs.yml
  media/readme-dockerhub.md
  package-lock.json
  package.json
Labels: documentation, size/M

#357 Prepare for next update
  .github/dependabot.yml
  .github/workflows/winget-release.yml
  README.md
  media/readme-dockerhub.md
  package-lock.json
  package.json
Labels: documentation, size/S
